---
title: "Cricket Dashboard"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r}
library(dplyr)
library(ggplot2)
odi = read.csv('e:/datasets/odi-batting.csv')
odi$MatchDate = as.Date(odi$MatchDate, format="%m-%d-%Y")
odi$year = format(odi$MatchDate, "%Y")
uniq_years = sort(unique(as.numeric(odi$year)))
uniq_countries = unique(odi$Country)
```


Sidebar {.sidebar}
====================================
```{r}
selectInput(inputId = "select_country", label = "Select a country",
            choices = uniq_countries)
#selectInput(inputId = "select_year", label="Select a Year",
#            choices = uniq_years)
sliderInput(inputId = "slide_year", label="Select a Year",
            min=min(uniq_years), max=max(uniq_years), value=max(uniq_years))
```

Dashboard 
====================================

Row
------------------------

### Output

```{r}
renderPlot({
  odi %>% filter(Country == input$select_country, year==input$slide_year) %>% group_by(Player) %>% summarise(Runs=sum(Runs, na.rm = T)) %>% arrange(-Runs) %>% head(5) %>% ggplot(aes(x=reorder(Player, -Runs), y=Runs)) + geom_bar(stat='identity')
})
```


Row
------------------
### Output 3
```{r}
#renderText({input$select_bin})
```

### Date output
```{r}

```

